server:
  port: 8761
spring:
  application:
    name: pn-register-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:123456@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #enable-self-preservation: false #关闭注册中心自我保护模式
    eviction-interval-timer-in-ms: 30000 # 清理关闭服务间隔时间
security:
  user:
    name: user
    password: 123456
