server:
  port: 8080
  context-path: /pn
spring:
  application:
    name: pn-web
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
    healthcheck:
          enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
#feign.hystrix.enabled=true 这个最好都加上，因为有些版本默认是关闭的

#feign 日志
logging:
  level:
    com.example.user.feign: DEBUG
