server:
  port: 8088
spring:
  cloud:
    config: 
      server:
        git:
          uri: https://github.com/chenkuifang/pn-config-server
  application:
    name: config-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} #默认端口不行