server:
  port: 8085
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

#如果不设置该属性，访问zuul的 /routes时返回401；如果不设置可添加spring security 依赖即可
management:
  security:
    enabled: false

#是否开启重试功能
#zuul.retryable=true
##对当前服务的重试次数
#ribbon.MaxAutoRetries=2
##切换相同Server的次数
#ribbon.MaxAutoRetriesNextServer=0

    
zuul:
  routes:
    user:
      path: /user/**
      serviceId: pn-user
      #省略服务名称路径前缀
      strip-prefix: false
      #多实例配置
      #ribbon.eureka.enabled=false
      #pn-user-.ribbon.listOfServers=http://localhost:8080/,http://localhost:8081/


    goods:
      path: /goods/**
      serviceId: pn-goods
      strip-prefix: false

    order:
      path: /order/**
      serviceId: pn-order
      strip-prefix: false

  retryable: true #是否开启重试功能

