server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} #默认端口不行


spring:
    #mysql tomcat连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;autoReconnectForPools=true
    username: root
    password: 123456
  couchbase:
    env:
      ssl:
        enabled: false
  zipkin:
    base-url: http://localhost:9411  # 配置信息到zipkin服务 （默认网址）

  ####################### kafka config #########################
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 10.80.1.110:9092
    consumer:
      bootstrap-servers: 10.80.1.110:9092
      group-id: test #消费群
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#resource目录下的mapper包下的所有xml文件
#mybatis.mapper-locations=classpath:mapper/*.xml
#指定实体包下的类别名
#mybatis.type-aliases-package=com.example.demo.entity
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.common.entity

#---------------------日志设置--------------#
#springboot 默认提供 logback日志框架
#mybatis sql语句打印
#logging.level.com.example.demo.mapper=debug
logging:
  level:
    com:
      example:
        mapper: debug

#需要未授权访问Acuator 端点
management:
  security:
    enabled: false
#    roles: ADMIN
#security:
#  user:
#    name: admin
#    password: 123456

